version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        GIT_BRANCH: UI-Modification--Use-Material-UI
    image: attend-backend:latest
    env_file:
      - server/.env
    ports:
      - "5000:5000"
    networks:
      - attend-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        GIT_BRANCH: UI-Modification--Use-Material-UI
        VITE_API_BASE_URL: "http://backend:5000/api"
        VITE_USE_RELATIVE_API_URL: "true"
    image: attend-frontend:latest
    environment:
      # ensure parity between build-time and run-time
      VITE_API_BASE_URL: "http://backend:5000/api"
      VITE_USE_RELATIVE_API_URL: "true"
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - attend-network

networks:
  attend-network:
    driver: bridge
