version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: attend-backend:latest
    env_file:
      - server/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_USE_RELATIVE_API_URL: ${VITE_USE_RELATIVE_API_URL}
    image: attend-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
