services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        GIT_BRANCH: UI-Modification--Use-Material-UI
    image: attend-backend:latest
    env_file:
      - server/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        GIT_BRANCH: UI-Modification--Use-Material-UI
        VITE_API_BASE_URL: /API
        VITE_USE_RELATIVE_API_URL: "true"
    image: attend-frontend:latest
    ports:
      - "9000:80"
    depends_on:
      - backend
