
require('dotenv').config();
const { sql } = require('../config/db');
const bcrypt = require('bcrypt');

async function debugLogin(targetUser, targetPasswordHash) {
  // Use environment variables directly for connection
  const config = {
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    server: process.env.DB_SERVER,
    database: process.env.DB_NAME,
    options: {
      encrypt: true,
      trustServerCertificate: true
    },
    port: parseInt(process.env.DB_PORT) || 1433
  };

  console.log(`\n🔍 Debugging login for user: '${targetUser}'`);
  console.log(`Expected Hash: ${targetPasswordHash.substring(0, 15)}...`);

  try {
    const pool = await sql.connect(config);
    console.log('✅ Connected to database');

    const query = "SELECT * FROM users WHERE username = @target";
    const result = await pool.request()
      .input('target', sql.NVarChar, targetUser)
      .query(query);

    if (result.recordset.length === 0) {
      console.log('❌ User NOT found in database.');
    } else {
      const user = result.recordset[0];
      console.log('\n✅ User FOUND:');
      console.log(`- ID: ${user.id}`);
      console.log(`- Username: '${user.username}'`);
      // console.log(`- Email: '${user.email}'`); // Email column does not exist
      console.log(`- Stored Password: '${user.password}'`);
      
      // Check if stored password matches the provided hash (meaning the DB has the hash we expect)
      if (user.password === targetPasswordHash) {
        console.log('✅ Database hash matches the expected hash exactly.');
        
        // Note: We cannot test bcrypt.compare without the actual password
        console.log('ℹ️  Since the hash matches, the issue is likely:');
        console.log('   1. The password being typed is incorrect');
        console.log('   2. The hash algorithm/cost used to generate this hash differs from what the server expects (unlikely for $2b$)');
        
        // Let's create a test hash with "password123" to compare formats
        const testHash = await bcrypt.hash('password123', 10);
        console.log(`\nTest Hash generated by this server (for 'password123'): ${testHash}`);
        console.log(`Prefix check: ${testHash.substring(0, 4)} vs ${user.password.substring(0, 4)}`);
        
      } else {
        console.log('❌ Database hash DOES NOT match the expected hash.');
        console.log(`   Stored:   ${user.password}`);
        console.log(`   Expected: ${targetPasswordHash}`);
      }
    }

    await pool.close();
  } catch (err) {
    console.error('Error:', err);
  }
}

// Run with the specific user and hash provided
debugLogin(
  'widji.santoso@merdekabattery.com', 
  '$2b$10$6RDmlFRrBYGYRaC0iocjY.Liszb5JC7Jte0s11RY6HvvsjD5IDUq.'
);
