FROM node:22-alpine
WORKDIR /usr/src/app

# install prod deps
COPY server/package.json server/package-lock.json ./
RUN npm ci --production

# copy source code only
COPY server/src ./src

EXPOSE 5000

# run your server.js directly with node
CMD ["node", "src/server.js"]
