FROM node:22-alpine
WORKDIR /usr/src/app

# install prod deps
COPY server/package.json server/package-lock.json ./
RUN npm ci --production

# copy source + env
COPY server/src ./src
COPY server/.env ./.env      # PORT=5000 etc.

EXPOSE 5000
CMD ["npm", "start"]          # runs `node src/server.js`
